### ISSUE TITLE
User broy - Can not edit tour1.

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#110]
1. Goes on tour have id the old tour
2. Clicks on Edit button 
3. Change value of name 
4. Clicks on "Edit" button . 
5. Change name 
7. Clicks on "Update" 
Actual results : when user clicks on 'Update " don't close popup then . Don't save data success . Goes on this tour and clicks on priview -> show view wrong . we get 2 tour will goes one one page when user clicks on privew , 
![edit](https://user-images.githubusercontent.com/13676159/31974677-3573f418-b957-11e7-93bf-7664c2a03432.png)
![edit_1](https://user-images.githubusercontent.com/13676159/31974679-3805a140-b957-11e7-97c6-7cd66434e565.png)
![edit_2](https://user-images.githubusercontent.com/13676159/31974680-3b0a558e-b957-11e7-918a-bed072752764.png)

**Comment by jooservices** [comment]
Resolved
