### ISSUE TITLE
Missing all datas of tour then user edit hosthot 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#111]
1. goes on edit hostpot of tour
2. Add some hostpot and clicks on "Save"
3. Save success. 
4. Goes on Edit tour 
Actual results : Can't see any info of tour
![edit_host_hot](https://user-images.githubusercontent.com/13676159/31974928-628ee0a6-b958-11e7-9dfe-a5bf787bbca0.png)
Clicks on "hostpot" and can't see any infor of tour . Just Preview is wrork
![ehit_hostpot_1](https://user-images.githubusercontent.com/13676159/31974962-98a0344c-b958-11e7-9e3c-3bd82690c691.png)

**Comment by jooservices** [comment]
Resolved
