### ISSUE TITLE
User broy - Upload image have is JPG still show "file valid" but can not save 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#113]
1. Goes on add image for tour 
2. Make sure image is .JPG
3. clicks on Update 
actual results : can not save

![iamge_png](https://user-images.githubusercontent.com/13676159/31983919-9a6f2dec-b989-11e7-9092-9e5ff1e34e96.png)

**Comment by jooservices** [comment]
Resolved
