### ISSUE TITLE
User broy - Then Update tour fail website show wrong form image 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#114]
1. Goes on edit tour . make sure this tour have image . 
2. Upload image is /JPG'
3. Clicks on "Udpate" 
4. cAn not update success . 
actual results . Form show name of image change is field . Here your can change name of image  
Expected results : when update some things is wrong , please don't change form of image 
![iamge_png](https://user-images.githubusercontent.com/13676159/31984134-81ce9da8-b98a-11e7-9a2b-a00e6106164b.png)
![udpate_fail](https://user-images.githubusercontent.com/13676159/31984137-8744ce92-b98a-11e7-94eb-758f66ffd355.png)
![udpate_faile_remove](https://user-images.githubusercontent.com/13676159/31984142-8aa32b1a-b98a-11e7-8173-91c76f5ab184.png)

**Comment by jooservices** [comment]
Resolved
