### ISSUE TITLE
Create new Tour - Button create new not working

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#122]
1. Add new tour
2. Fill in valid value for all field and add image
3. Clicks on "Create new"
Actual results : Nothing happen then user clicks on "Create new" 

![image](https://user-images.githubusercontent.com/13676159/32756793-79be2db6-c90e-11e7-9221-dd65be5547d0.png)

**Comment by jooservices** [comment]
Resolved
