### ISSUE TITLE
Create when missing pano title and pano subtitle

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#123]
1. Create new Tour
2. fill in name and add image for tour . 
3. Make sure you will missing pano title and sub title of page /
4/. Clicks on "Create new" 
ACtual restuls : -> do not show up alter missing field 
![image](https://user-images.githubusercontent.com/13676159/32757087-396c2978-c910-11e7-82c5-11a914896c93.png)

**Comment by jooservices** [comment]
Resolved
