### ISSUE TITLE
Set default view not working

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#125]
1. Goes on hostpot tab of tour nametorud592 and add hostpot looklike image 
![image](https://user-images.githubusercontent.com/13676159/32757758-b5fff372-c913-11e7-9050-ccd833228764.png)
2. Save success and goes on preview 
Actual results 
![image](https://user-images.githubusercontent.com/13676159/32757770-c79a91c8-c913-11e7-8c50-c932b466b068.png)

position default not the same when user at .

**Comment by jooservices** [comment]
Resolved
