### ISSUE TITLE
Login Page - "Send" icon working incorrect  

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#27]
![capture 2017-09-02 at 8 06 08](https://user-images.githubusercontent.com/13676159/30599566-bf5b97ce-9d11-11e7-8a05-8bc138e217c6.png)

**Comment by jooservices** [comment]
That's email. Click on it will open email client and pre-filled with our email. So, please check if you click on it and can see mail client opened ! @nhungnguyen123

**Comment by nhungnguyen123** [comment]
![image](https://user-images.githubusercontent.com/13676159/30600944-8d2d0af4-9d15-11e7-85d6-b1da2bd3c0bb.png)

This page show me " mailto:info@globalvision.ch " . Please confirm .

**Comment by jooservices** [comment]
Not like that . But i think you have no email client ? I will verify this one.

Thanks

**Comment by jooservices** [comment]
This one should be fixed. Remove _blank
