### ISSUE TITLE
Login page - show wrong message when user fills in wrong value . 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#28]
Please follow steps : 
1. Fills in username : designteam
2. Fills in password : 1234 
3. Clicks on "Login : button 
Actual results : webpage show up clear page . 
Expected results : still keep "login page " and show message show user " password invalid' 
![capture 2017-09-02 at 8 11 05](https://user-images.githubusercontent.com/13676159/30600144-88fcc0c0-9d13-11e7-9a2a-33b886f0082c.png)
![capture 2017-09-02 at 8 11 11](https://user-images.githubusercontent.com/13676159/30600152-8dec8994-9d13-11e7-994c-4badd9b646b3.png)

**Comment by nhungnguyen123** [comment]
This issues work great . but when I testing with username invalid but this message still is" password invalid"
I think ,when user or password not make sense . We should show content is " Username or password invalid " Sorry about my suggest above . 
![capture 2017-09-00 at 17 57 59](https://user-images.githubusercontent.com/13676159/30781930-ae56823c-a152-11e7-89b3-2d82f3657cf9.png)

**Comment by jooservices** [comment]
Should be fixed.
