### ISSUE TITLE
Home page - "Embed" button working incorrect

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#29]
1. Login successfully , 
2. Goes on Home page . 
3. Clicks on "Embed" at any tour, . 
Actual restuls : We get error code here . 
![capture 2017-09-02 at 8 28 08](https://user-images.githubusercontent.com/13676159/30600703-0a518a2e-9d15-11e7-92ad-37befd08ad7a.png)

**Comment by jooservices** [comment]
@nhungnguyen123 Please always provide error included in screenshot

**Comment by nhungnguyen123** [comment]
error message : 
![error](https://user-images.githubusercontent.com/13676159/30602110-79fd4072-9d18-11e7-9e17-7036ef5eb29f.PNG)

**Comment by jooservices** [comment]
This one should be fixed.

**Comment by nhungnguyen123** [comment]
Hi @jooservices  . I don't make sure this page is right. Please give me more infor to confirm, Thanks a lot.
![capture 2017-09-05 at 6 59 09](https://user-images.githubusercontent.com/13676159/30748014-c98ccf52-9f63-11e7-8770-6ed51ea772d9.png)

**Comment by nhungnguyen123** [comment]
If this jframe is fine , Please close this issues . Thanks .

**Comment by jooservices** [comment]
Yay ! That's right. Client can copy that text and use it.
BUT you can raise IMPROVEMENT issue with: Provide copy button or automatic copy to clipboard ( and notice it ) so client can use it easier .

**Comment by nhungnguyen123** [comment]
Okay @jooservices  . I get it . Thanks
