### ISSUE TITLE
Can not preview tour 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#32]
1. Login success
2. Goes on home page .
3. Clicks on "New" button ,.
4. Fill in valid value and choice valid image.
5. Clicks on checkbox of "Check for auto rotation." and " Check for show media social button."
clicks on "Create new vTour" button .
6. Webpage create tour success and show this tour ,
7. User clicks on "Preview " button 
Actual result : can not show turn . Webpage show Null data . 
![capture 2017-09-02 at 9 01 47](https://user-images.githubusercontent.com/13676159/30603109-64ae026c-9d1b-11e7-870e-299c0b5def98.png)
![capture 2017-09-02 at 9 13 37](https://user-images.githubusercontent.com/13676159/30603119-6b5fdacc-9d1b-11e7-8165-ee3a02714d87.png)
![capture 2017-09-02 at 9 14 05](https://user-images.githubusercontent.com/13676159/30603124-6dbd0bfa-9d1b-11e7-8eb2-c97102cedf99.png)

**Comment by jooservices** [comment]
Is it working fine on live site ? @nhungnguyen123

**Comment by nhungnguyen123** [comment]
it is working fine . I will close this issues
