### ISSUE TITLE
Edit tour - Panorama - save description of Panorama look strange

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#33]
1. Goes on any tour
2. Clicks on " Edit" button .
3. Change description of "Panorama " is " Skype testing " 
4. Clicks on "Update " button 
5. Save this tourn success
Actual results : this description will show up is "Skypetesting"

![capture 2017-09-02 at 9 20 27](https://user-images.githubusercontent.com/13676159/30603537-ab463ec8-9d1c-11e7-89f8-207f38f507ed.png)
![capture 2017-09-02 at 9 20 53](https://user-images.githubusercontent.com/13676159/30603542-b260d9ca-9d1c-11e7-9f36-d52cfd158c8d.png)

**Comment by jooservices** [comment]
I can see it working fine for now.
