### ISSUE TITLE
Edit tour with change "Panorama" working incorrect 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#34]
1. Create one Tour with 2 "Panorama" 
2. Clicks on "Create" success . 
3. Clicks on edit button for this tour 
4. Clicks on "Remove Panorama" button for remove one "Panorama" 5. 
5. Clicks on "Update " button 
6.  Update succes and we got this tour with one "Panorama"
7. Clicks on "edit" button at this tour again, 
8. Add new "Panorama" for this tour.,
9. Clicks on " Update " button 

Actual results :  We got new tour with new url friend . 
![capture 2017-09-02 at 9 34 44](https://user-images.githubusercontent.com/13676159/30604365-7b95b804-9d1f-11e7-87ae-e576160abdc2.png)
![capture 2017-09-02 at 9 34 54](https://user-images.githubusercontent.com/13676159/30604374-82fb2746-9d1f-11e7-89e4-0e08fd3ff03c.png)
![capture 2017-09-02 at 9 35 04](https://user-images.githubusercontent.com/13676159/30604380-88119efe-9d1f-11e7-878a-e24349672dca.png)
![capture 2017-09-02 at 9 19 53](https://user-images.githubusercontent.com/13676159/30604410-a24edaca-9d1f-11e7-861b-cd0fc4477fdf.png)
![capture 2017-09-02 at 9 39 56](https://user-images.githubusercontent.com/13676159/30604425-b02977b8-9d1f-11e7-83e5-ebc82e230e4b.png)

**Comment by jooservices** [comment]
Nice catch !!! @nhungnguyen123 . I'll handle this one

**Comment by jooservices** [comment]
This one should be done. Please QA it. @nhungnguyen123

**Comment by nhungredweb** [comment]
Hi @jooservices  . testing again with add mote parona and can't update success . Please check this issues again . This is image i catch when add more panora . 
![screenshot from 2017-09-25 12-36-06](https://user-images.githubusercontent.com/23624614/30794421-2dcead10-a1f2-11e7-9f2b-3080158f95f3.png)
