### ISSUE TITLE
Can't accept create new tour when "Panorama " missing "Title " and "Description"

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#35]

**Comment by nhungnguyen123** [comment]
![capture 2017-09-02 at 9 50 31](https://user-images.githubusercontent.com/13676159/30604531-113e8944-9d20-11e7-8f1c-6012a04e4a8a.png)

**Comment by jooservices** [comment]
I don't think we have this issue. But please check and fix it if it's exists @nhan27

**Comment by nhanpc** [comment]
Actually, by default, "Title " and "Description" required fields.  Make sure it have validated.
If new spec is not required, we need to make it `string(0)''` or `string(1)' '` as default value in validate function.

**Comment by jooservices** [comment]
Applied required for both of fields.
At the moment no "error" friendly show up. Please raise another issue for improvement ( if this issue is passed ) @nhungnguyen123

**Comment by nhungnguyen123** [comment]
still create Tour without Pano sub title . please check this case again . Thanks 
![capture 2017-09-05 at 6 56 17](https://user-images.githubusercontent.com/13676159/30747824-3c8d5f9a-9f63-11e7-8ae1-fade07d06d6e.png)

**Comment by jooservices** [comment]
@nhan27 I have applied required for fields. But it's not working correctly. Please inspect it.

**Comment by jooservices** [comment]
This one should be fixed
