### ISSUE TITLE
"Hotspot " - share social working incorrect

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#37]
![capture 2017-09-02 at 9 56 33](https://user-images.githubusercontent.com/13676159/30604921-1c77f790-9d21-11e7-9654-7bdc8ff509dd.png)

**Comment by jooservices** [comment]
I will work on server side to save config into params['social']. After that please use it at your side.

**Comment by jooservices** [comment]
@nhan27

**Comment by jooservices** [comment]
In Add / Edit hotspot i think we don't need show socials buttons.. Or maybe need ? Please give me information about this one @nhan27

**Comment by jooservices** [comment]
I will close this one even no QA yet @nhungnguyen123
