### ISSUE TITLE
Hostpot - "Save" button not working 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#39]
![host](https://user-images.githubusercontent.com/13676159/30605178-f9781562-9d21-11e7-98d0-4537b94681b3.PNG)

**Comment by jooservices** [comment]
@nhan27 Please also make "iframe" full width of modal

**Comment by nhanpc** [comment]
@nhungnguyen123 can you plz add more details about this issue?
It is work fine with me?

![image](https://user-images.githubusercontent.com/26210491/30646085-f95f8918-9e41-11e7-97bb-5fa9e610d613.png)

**Comment by nhungnguyen123** [comment]
1. Goes on tour with id is "6154" 
2. Clicks on " Hostpot" 
3. Webpage show popup
4. Clicks on "Save" button 
6. Open console . you can see error . cc  @nhanpc

**Comment by nhanpc** [comment]
@jooservices

1.  /layouts/form/hotspots.php was not uptodate with https://github.com/jooservices/vr360.globalvision.dev/blob/master/layouts/form/hotspots.php
Can you please ssh and run git command to make sure all file are updated :? Thank you.

**Comment by nhanpc** [comment]
@nhungnguyen123 can you help me to test another features of "edit hotspot" ? Thank you lots.

**Comment by jooservices** [comment]
did you updated it into live site ?

**Comment by nhan27** [comment]
Yep.

.:pham.channhan:.
GOD bless and beside you

**Comment by nhungnguyen123** [comment]
I still seem this issues don't work . Hi @nhan27  , do you update somethings here .
