### ISSUE TITLE
Hostpot - Need to remove text popup when add new hostpot

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#43]
1. Clicks on "HostPot" have id id "6154"
2. Webpage show 3 image . Click every point and clicks on " ADD Hostpot "
3. Webpage show "Choose hostpot type" content 
4. Clicks on "Text Popup " 
5. Fill in field value is " Slky " 
6. Clicks on "Done" button
7. Webpage save success . 
8. Clicks on " ADD Hostpot " button gain . 
9 . Cliks oon " Text Popup " button . 
Actual restuls : this field show " Sky " again . 
Expected results : please remove empty field when add other Hostpost
![capture 2017-09-03 at 6 14 52](https://user-images.githubusercontent.com/13676159/30646014-6363c5a2-9dcc-11e7-8b70-e7ea56ebb39b.png)
![capture 2017-09-03 at 6 15 14](https://user-images.githubusercontent.com/13676159/30646019-66b9ec2c-9dcc-11e7-8791-abc79c45af74.png)

**Comment by jooservices** [comment]
@nhan27  please let me know if you can work on this one. It's all about js

**Comment by nhanpc** [comment]
@jooservices I will work on this.

**Comment by jooservices** [comment]
How's going ? @nhan27

**Comment by jooservices** [comment]
Resolved
