### ISSUE TITLE
Home page - search by name or ID 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#44]
Please , make search function for this page . 
![capture 2017-09-03 at 6 36 44](https://user-images.githubusercontent.com/13676159/30646539-36c8c842-9dce-11e7-9eaf-20b60c6297f6.png)

**Comment by jooservices** [comment]
Duplicated https://github.com/jooservices/vr360.globalvision.dev/issues/12
