### ISSUE TITLE
Edit tour without name need show tooltip at the first time user clicks on " Update" button

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#46]
1. Goes on Home page . 
2. Clicks on "edit" button at any tour. 
3. User remove name of this tour , 
4. Clicks on "Update " button 
5. Nothing hapeen 
6. User clicks on "Update " button again . 
7. Webpage show tooltip at field name . 
Expected result : when the first time use clicks on "Update " without name or "URL friendly" . We need to check and show tooltip immediately
![capture 2017-09-03 at 6 45 10](https://user-images.githubusercontent.com/13676159/30647450-4c29d1ca-9dd0-11e7-8931-58dc1cbcf8a3.png)
![capture 2017-09-03 at 6 45 56](https://user-images.githubusercontent.com/13676159/30647457-51e4e690-9dd0-11e7-954e-9ccb9e094519.png)

**Comment by jooservices** [comment]
Resolved @nhungnguyen123
