### ISSUE TITLE
Can not create new tour

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#48]
1. Goes on Home page 
2. Clicks on "New" button 
3. Fill in valid value .
4. Clicks on "Create new vTour " button 
Acutal result : Can not create new tour with one image inside , Webpage show alert look so strange , Yesterday , I can create success ,. Please check this case again . thanks
![save_new](https://user-images.githubusercontent.com/13676159/30649905-5e7b9510-9dd6-11e7-85b1-29ff550c74a0.PNG)

**Comment by nhanpc** [comment]
```
<br />
<b>Warning</b>:  file_put_contents(./_/__59c28ad773b32_85452ecabf6e1e341b5c2045e0170167/vtour/tour.xml): failed to open stream: No such file or directory in <b>/home/clients/51ba02838bed5891d60f0685fadfb1d6/subdomains/vr360.globalvision.ch/libraries/helper/tour.php</b> on line <b>199</b><br />
{"data":null,"messages":["<span class=\"label label-warning\">Can not generate xml for vTour<\/span>"],"status":false}
```

**Comment by nhanpc** [comment]
Solved. @nhungnguyen123 can you please test again? thank you :)

**Comment by jooservices** [comment]
Look like it works but please double check on crossing browser and with multi ( lots ) panos .
@nhungnguyen123

**Comment by jooservices** [comment]
This issue should be worked fine. But MySQL issue is another thing at server side.
