### ISSUE TITLE
Provide all required meta data for SEO in tour view

### ISSUE THREAD

**Issue by jooservices** [jooservices/vr360.globalvision.dev#49]

**Comment by jooservices** [comment]
This one should be fixed. But need get right default thumbnail

**Comment by nhungnguyen123** [comment]
Hi @jooservices . can you explain more infomation for me at this issues ? Thanks a lot

**Comment by jooservices** [comment]
# Please share tour view ( URL when you use "preview" ) on any social network
- It should fetch right thumbnail ( atm we are using first thumbnail as default - but when will @nhan27  fixed issue with default pano, we'll use thumbnail of default pano )

Actually i would suggest raise another improvement issue allow provide keyword / description for each tour, and apply it into tour view.
Atm we are using default from configuration.

**Comment by jooservices** [comment]
This one should be fixed
