### ISSUE TITLE
Allow to set default pano

### ISSUE THREAD

**Issue by jooservices** [jooservices/vr360.globalvision.dev#51]

**Comment by nhanpc** [comment]
Can you help me to add a default option next to the view of tour. then save the value into tour params? then I will do the rest. Thank you.
@jooservices

**Comment by jooservices** [comment]
You will have it today @nhan27

**Comment by jooservices** [comment]
It should be done. Please pull and work on it @nhan27

**Comment by jooservices** [comment]
Should be worked but no QA ? @nhungnguyen123  I will close this manual
