### ISSUE TITLE
Provide more required meta data for SEO in tour view 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#53]
![capture 2017-09-05 at 7 32 55](https://user-images.githubusercontent.com/13676159/30749526-870328e8-9f68-11e7-87d0-db9822b32196.png)
- Check with facebook. Please input more infor foe "alt" .Thanks 
![capture 2017-09-05 at 7 34 50](https://user-images.githubusercontent.com/13676159/30749578-af631fdc-9f68-11e7-979c-0ddf5e7e60d2.png)

**Comment by jooservices** [comment]
This one should be fixed
