### ISSUE TITLE
Tour - Accept input description and key for strong SEO

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#54]
When create new tour . At this form , we should make field description and key for user input value. 
2 field above will make SEO strong .

**Comment by jooservices** [comment]
keyword.
And if user did not provide it we can use default from configuration.

**Comment by jooservices** [comment]
I believe we already had this one @nhungnguyen123 . Issue resolved.
Ps:// Please QA and if we have any issue please raise trello card
