### ISSUE TITLE
Use default pano / thumbnail

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#55]
![capture 2017-09-05 at 7 39 27](https://user-images.githubusercontent.com/13676159/30749775-42631c6a-9f69-11e7-81fd-1cde1357fa5d.png)

**Comment by jooservices** [comment]
- Allow to choose default pano
- Use thumbnail of this default pano for meta data
I have updated your instruction. @nhungnguyen123

**Comment by jooservices** [comment]
Should be resolved
