### ISSUE TITLE
Home page- Show content so strange

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#67]
1. Login with username/pass 
2. Login success
3. Clicks on "New" tour 
4. Fill in valid value at new tour from 
5. User clicks on " Create " tour 
6. Webpage create tour fail . 
7. Goes on home page and enter"F5" at keyboard
Actual results  Webpage show "invalid password " . Please check this case again . Thanks 
![capture 2017-09-00 at 16 20 49](https://user-images.githubusercontent.com/13676159/30781262-005ba5b0-a146-11e7-9597-e92c2021cc7d.png)

**Comment by jooservices** [comment]
Damn . I saw this in localhost but can't solve and guessing that's cache :| Will try to work on this.
Thanks

**Comment by jooservices** [comment]
Should be fixed

**Comment by jooservices** [comment]
No QA yet @nhungnguyen123
