### ISSUE TITLE
Result search need improve UI

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#69]
![search](https://user-images.githubusercontent.com/13676159/30782013-197bf5e6-a154-11e7-8105-a8251e69ef6a.png)
![results](https://user-images.githubusercontent.com/13676159/30782015-1bf4df04-a154-11e7-9541-d98476be05d2.png)
When user fill in name tour and enter at keyboard , Webpage show results  . We need create on option for refresh table  . Thanks

**Comment by jooservices** [comment]
Resolved
