### ISSUE TITLE
Hostpot- update more hostpot missing data 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#77]
1. goes on any tour and try to setup this tour have 2 hostpot. 
2. Update this tourn add plus one hostpot again 
3. clicks on save button 
4. save success . 
Actual results : this tour just have 1 hostpot 
Expected results: this tour must be have 3 hostpot when user update 
![Uploading add.png…]()
![add_more](https://user-images.githubusercontent.com/13676159/30890020-53dd92ba-a354-11e7-936a-7c964ddfc47c.png)
![Uploading add_result.png…]()

**Comment by jooservices** [comment]
Nice catch
