### ISSUE TITLE
Show hostpot - "Viet" tour - Missing hostpot at home page 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#96]
1. Add 2 hostpot at one image 
2. Clicks on "Save" button 
3. Check number At Home page 
Actual results : We have 2 hostpot but at home page just show 1 . 
Expected results : Show the number of hostpot correct
![2_host_pot](https://user-images.githubusercontent.com/13676159/31862922-a2cf3b64-b770-11e7-9c6c-61f76d5b027b.png)
![host_pot](https://user-images.githubusercontent.com/13676159/31862923-a40d3b02-b770-11e7-8a20-8568dd3f175d.png)

**Comment by nhungnguyen123** [comment]
i see you remote information about hostpot and pano at home page . are we should remove this ? Please confirm cc @jooservices ?

**Comment by jooservices** [comment]
Resolved
