### ISSUE TITLE
Show number of pano incorrect - "VietVu Testing" Tour 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#98]
1. Goes on home page and check number pano of "VietVu Testing" Tour -> Just show 1 pano
2. Clicks on "Edit" button of "VietVu Testing" Tour -> we have 2 panos here 
Actual results : Webpage show number of  "VietVu Testing" Tour at home page is incorrect . 
![pan](https://user-images.githubusercontent.com/13676159/31863106-ff28cf7c-b772-11e7-814f-7496d192149b.png)
![pano_2](https://user-images.githubusercontent.com/13676159/31863107-0096800c-b773-11e7-9efc-4ccf160fe392.png)

**Comment by jooservices** [comment]
Resolved
