### ISSUE TITLE
"VietVu Testing" Tour - Check for show media social button working incorrect 

### ISSUE THREAD

**Issue by nhungnguyen123** [jooservices/vr360.globalvision.dev#99]
1. Goes on "VietVu Testing" Tour and check value of "Check for show media social button" checkbox 
2. Clicks on " Preview " for see image detail :http://dev.globalvision.ch/viet-vu-testing 
Actual results : Check for show media social button" of  "VietVu Testing" Tour is un check but still show 3  social button. Please check data again . thanks .

**Comment by jooservices** [comment]
Please re-produce this issue with new tour. I can't check above URL because duplicated alias issue

**Comment by nhungnguyen123** [comment]
1. login with "spg" account  
2. Create one tour with one pano success . 
3. Make sure do not clicks on "show media social button working" button . 
4. Goes on priview and look at this image. -> don't have social button -> right.
5, Goes on edit of this tour and clicks on "show media social button working" button . 
6, Clicks on "Save" button , -> save success, 
7. goes on Preview again -> don't have button socical . \
![social_no](https://user-images.githubusercontent.com/13676159/31863799-3447142a-b77d-11e7-9049-fc485f73b716.png)
![no_oki](https://user-images.githubusercontent.com/13676159/31863809-434722bc-b77d-11e7-9356-a378f519e0c0.png)

**Comment by jooservices** [comment]
Make sure you are completely cleared cache after changed options.
Clear cache or check on another browser please. 
@nhungnguyen123

**Comment by nhungnguyen123** [comment]
This is cache . I will closed this .Thanks
